[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
payai_marketplace = "5FhmaXvWm1FZ3bpsE5rxkey5pNWDLkvaGAzoGkTUZfZ3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
generate-clients = "yarn ts-node ./scripts/generate-clients.ts"
init-global-state = "yarn ts-node ./scripts/init-global-state.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
update-admin = "yarn ts-node ./scripts/update-admin.ts"
